source 'http://rubygems.org'

ruby '2.2.2'

gem 'rack', '1.6.5'
gem 'sinatra'
gem 'omniauth-slack'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'carrierwave'
gem 'rake'
gem 'sqlite3'
gem 'actionpack', '~>4'
# gem 'activesupport', '~>4.2.7', require: 'active_support/all'
gem 'actionview'#, '~>4.2.7'
# gem 'actionview', '~> 4.1.0'
